2024-10-31 12:29:00.761 - INFO    - MainThread - client.py:204 [connectAsync] - Connecting to 127.0.0.1:7497 with clientId 32174...
2024-10-31 12:29:00.763 - INFO    - MainThread - client.py:212 [connectAsync] - Connected
2024-10-31 12:29:00.769 - INFO    - MainThread - client.py:341 [_onSocketHasData] - Logged on to server version 176
2024-10-31 12:29:00.775 - ERROR   - MainThread - decoder.py:189 [handler] - Error for managedAccounts:
Traceback (most recent call last):
  File "c:\Users\felin\AppData\Local\Programs\Python\Python313\Lib\site-packages\ib_insync\decoder.py", line 187, in handler
    method(*args)
    ~~~~~~^^^^^^^
  File "c:\Users\felin\AppData\Local\Programs\Python\Python313\Lib\site-packages\ib_insync\wrapper.py", line 241, in managedAccounts
    self.ib.managedAccounts(accountsList)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: IBStoreInsync.managedAccounts() takes 1 positional argument but 2 were given
2024-10-31 12:29:00.781 - INFO    - MainThread - client.py:218 [connectAsync] - API connection ready
2024-10-31 12:29:00.781 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:hfarm
2024-10-31 12:29:00.782 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:cashfarm
2024-10-31 12:29:00.783 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm.nj
2024-10-31 12:29:00.783 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2104, reqId -1: Market data farm connection is OK:usfarm
2024-10-31 12:29:00.783 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:euhmds
2024-10-31 12:29:00.784 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:apachmds
2024-10-31 12:29:00.784 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:fundfarm
2024-10-31 12:29:00.785 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2106, reqId -1: HMDS data farm connection is OK:ushmds
2024-10-31 12:29:00.785 - INFO    - MainThread - wrapper.py:1149 [error] - Warning 2158, reqId -1: Sec-def data farm connection is OK:secdefhk
2024-10-31 12:29:01.104 - INFO    - MainThread - ibstore_insync.py:2710 [connectAsync] - Synchronization complete
